name: Docker Image CI

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

env:
  PLATFORMS: linux/arm64
  DOCKERHUB_USERNAME: helllord
  DOCKERHUB_REPOSITORY: reverse-shell-generator
  TAG_GIT_COMMIT: 0dayCTF/reverse-shell-generator

jobs:
  get-tag:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.get-tag.outputs.tag }}
    steps:
      - name: Fetch get_tag.py
        uses: actions/checkout@v4
        with:
          repository: hellbot77/get-tag
          sparse-checkout: get_tag.py
          sparse-checkout-cone-mode: false
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3
      - name: Get Docker image tag
        id: get-tag
        run: python get_tag.py ${{ env.DOCKERHUB_USERNAME }}/${{ env.DOCKERHUB_REPOSITORY }} --git-commit ${{ env.TAG_GIT_COMMIT }} >> $GITHUB_OUTPUT
  build-push:
    needs: get-tag
    if: ${{ needs.get-tag.outputs.tag }}
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Dockerfile
        uses: actions/checkout@v4
        with:
          sparse-checkout: Dockerfile
          sparse-checkout-cone-mode: false
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: ${{ env.PLATFORMS }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: ${{ env.PLATFORMS }}
          push: true
          build-args: TAG=${{ needs.get-tag.outputs.tag }}
          tags: |
            ${{ env.DOCKERHUB_USERNAME }}/${{ env.DOCKERHUB_REPOSITORY }}:${{ needs.get-tag.outputs.tag }}
            ${{ env.DOCKERHUB_USERNAME }}/${{ env.DOCKERHUB_REPOSITORY }}:latest
  cancel-action:
    needs: get-tag
    if: ${{ !needs.get-tag.outputs.tag }}
    runs-on: ubuntu-latest
    steps:
      - name: Cancel action
        uses: andymckay/cancel-action@0.3
      - name: Wait for cancel
        run: sleep infinity
